import { IValidation } from "../models/validation.interface";

export const VALIDATION_CRITERIA: IValidation = {
  emailMaxLength: 100,
  passwordMinLength: 8,
  passwordMaxLength: 15,
  nameMinLength: 3,
  nameMaxLength: 80,
  phoneMinLength: 10,
  phoneMaxLength: 10,
  descriptionMinLength: 3,
  descriptionMaxLength: 500,
  priceMinLength: 1,
  priceMaxLength: 10,
  minFloor: 0,
  maxFloor: 20,
  minArea: 100,
  maxArea: 10000,
  houseNumberMinLength: 1,
  houseNumberMaxLength: 100,
  streetMinLength: 3,
  streetMaxLength: 100,
  zipcodeMinLength: 4,
  zipcodeMaxLength: 12,
  taxNumberMinLength: 3,
  taxNumberMaxLength: 40,
  regNumberMinLength: 3,
  regNumberMaxLength: 40,
  landmarkMinLength: 3,
  landmarkMaxLength: 140,
  bioMinLength: 3,
  bioMaxLength: 140,
  addressMinLength: 3,
  addressMaxLength: 140,
  phoneNumber: 10,
  subjectMaxLength: 250,
};
